import fs from 'node:fs';

// // console.log('fs', 'write' in fs);

export const plants = [
  {
    id: 1,
    name: 'alocasia cucullata',
    origin: 'China, India, Sri Lanka, Burma',
    careWater: 3,
    careLight: 2,
    careFertilize: 1,
    price: 24.99,
    description: 'lorem ipsum',
  },
  {
    id: 2,
    name: 'monstera',
    origin: 'Mexico, Panama',
    careWater: 1,
    careLight: 1,
    careFertilize: 1,
    price: 30.99,
    description: 'lorem ipsum',
  },
  {
    id: 3,
    name: 'philodendron red cherry',
    origin: 'Caribbean, Colombia, Venezuela',
    careWater: 3,
    careLight: 2,
    careFertilize: 2,
    price: 19.99,
    description: 'lorem ipsum',
  },
  {
    id: 4,
    name: 'scindapsus pictus',
    origin: 'Southeast Asia',
    careWater: 3,
    careLight: 2,
    careFertilize: 2,
    price: 19.99,
    description: 'lorem ipsum',
  },
  {
    id: 5,
    name: 'anthurium clarinervium',
    origin: 'Mexico',
    careWater: 3,
    careLight: 2,
    careFertilize: 2,
    price: 24.99,
    description: 'lorem ipsum',
  },
  {
    id: 6,
    name: 'peperomia polybotrya',
    origin: 'Central America',
    careWater: 3,
    careLight: 2,
    careFertilize: 2,
    price: 19.99,
    description: 'lorem ipsum',
  },
];
